---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: PROJECT_NAME
  name: PROJECT_NAME
  namespace: NameSpace
spec:
  replicas: Replicas
  selector:
    matchLabels:
      app: PROJECT_NAME
  template:
    metadata:
      labels:
        app: PROJECT_NAME
    spec:
      containers:
      - image: harborAddress/BRANCH_NAME/PROJECT_NAME:BUILD_ID
        imagePullPolicy: Always
        name: PROJECT_NAME
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: PROJECT_NAME
  namespace: NameSpace
spec:
  ports:
  - name: port-admin
    nodePort: 3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: PROJECT_NAME
  type: NodePort
